destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/home-pdf"
port: 4010
output: pdf
product: HRM Nirvana
print_title: HRM Documentation 
print_subtitle: version 1.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: home_sidebar
